### ISSUE TITLE
Time to fix some issues

### ISSUE THREAD

**Issue by zuzannast** [netguru-code-college/vol2-alpha#48]
1. Define [model scope](http://api.rubyonrails.org/classes/ActiveRecord/Scoping/Named/ClassMethods.html) for the query used in your controller: https://github.com/netguru-code-college/vol2-alpha/blob/master/app/controllers/meetups_controller.rb#L5
2. You can move this sorting to a model class method: https://github.com/netguru-code-college/vol2-alpha/blob/master/app/controllers/users_controller.rb#L4
3. https://github.com/netguru-code-college/vol2-alpha/blob/master/app/controllers/users_controller.rb#L18 & https://github.com/netguru-code-college/vol2-alpha/blob/master/app/controllers/opinions_controller.rb#L18-L19 
Extract assigning variables that are used in multiple actions to a private method and call this in a before_action. Example: https://github.com/netguru-code-college/todo_list/blob/master/app/controllers/lists_controller.rb#L2
4. This should be moved to a class Decorators https://github.com/netguru-code-college/vol2-alpha/blob/master/app/models/meetup.rb#L36-L38 & https://github.com/netguru-code-college/vol2-alpha/blob/master/app/models/user.rb#L56-L62
5. You can create a [Service object](https://www.netguru.co/blog/service-objects-in-rails-will-help) to calculate this rating
6. Please run rubocop locally and check for styling issues. You can use custom config from [our TodoList app](https://github.com/netguru-code-college/todo_list/blob/0cb441eb2507caa81d4469f85a9b9cd66c3ebc76/.rubocop.yml). After fixing the issues, please add rubocop check to your Travis config file.

Happy Coding 👏

**Comment by xkwd** [comment]
All fixed in #59
